version = "0.6.2"
content_dir = "content"
formats = ["html"]

[spine]
exclude = ["nest/template.typ"]

[html.assets]
css_stylesheet = "./style.css"
js_scripts = "./index.js"

[packages.rookery]
repo = "https://github.com/freecomputinglab/rookery"
branch = "dev"
