#import "template.typ": template
#import "@rookery/core:0.1.1": idea

#set document(title: [Authors])
#show: template.with(current-page: "nest:authors")

#let person = idea.with(tag: "person")

#person(<kermode-lachlan>, title: [Lachlan Kermode])[]
#person(<stewart-william>, title: [William Stewart])[]
#person(<case-holly>, title: [Holly Case])[]
#person(<vanburns-austen>, title: [Austen Van Burns])[]

#person(<herbert-mehrtens>, title: [Herbert Mehrtens])[]
#person(<jeremy-gray>, title: [Jeremy Gray])[]
#person(<sarah-pourciau>, title: [Sarah Pourciau])[]
#person(<aaron-scott>, title: [Scott Aaronson])[]
#person(<atiyah-michael>, title: [Michael Atiyah])[]
#person(<avigad-jeremy>, title: [Jeremy Avigad])[]
#person(<babbage-charles>, title: [Charles Babbage])[]
#person(<benacerraf-paul>, title: [Paul Benacerraf])[]
#person(<berkeley-george>, title: [George Berkeley])[]
#person(<castelle-michael>, title: [Michael Castelle])[]
#person(<deringer-william>, title: [William Deringer])[]
#person(<henkle-jonah>, title: [Jonah Henkle])[]
#person(<horl-erich>, title: [Erich Hörl])[]
#person(<husserl-edmund>, title: [Edmund Husserl])[]
#person(<joque-justin>, title: [Justin Joque])[]
#person(<krieger-martin>, title: [Martin Krieger])[]
#person(<longo-giuseppe>, title: [Giuseppe Longo])[]
#person(<marx-george>, title: [George Marx])[]
#person(<marx-karl>, title: [Karl Marx])[]
#person(<mazzotti-massimo>, title: [Massimo Mazzotti])[]
#person(<meli-domenico>, title: [Domenico Meli])[]
#person(<miller-jacques>, title: [Jacques Miller])[]
#person(<naderi-reza>, title: [Reza Naderi])[]
#person(<peirce-charles>, title: [Charles Peirce])[]
#person(<poincare-henri>, title: [Henri Poincaré])[]
#person(<propp-james>, title: [James Propp])[]
#person(<rodin-andrei>, title: [Andrei Rodin])[]
#person(<ruda-frank>, title: [Frank Ruda])[]
#person(<schmid-eric>, title: [Eric Schmid])[]
#person(<serres-michel>, title: [Michel Serres])[]
#person(<siegert-bernhard>, title: [Bernhard Siegert])[]
#person(<weatherby-leif>, title: [Leif Weatherby])[]
#person(<vasilie-na-a>, title: [N. A. Vasiliev])[]
#person(<vonfoerster-heinz>, title: [Heinz Von Foerster])[]
#person(<vonneumann-john>, title: [John von Neumann])[]
#person(<warwick-andrew>, title: [Andrew Warwick])[]
#person(<thurston-william>, title: [William P. Thurston])[]
#person(<turing-alan>, title: [Alan Turing])[]
#person(<steingart-alma>, title: [Alma Steingart])[]
#person(<bernoulli-daniel>, title: [Daniel Bernoulli])[]
#person(<bernoulli-johann>, title: [Johann Bernoulli])[]
#person(<jing-felicia>, title: [Felicia Jing])[]
#person(<handelman-matthew>, title: [Matthew Handelman])[]
#person(<adorno-theodor>, title: [Theodor Adorno])[]
#person(<horkheimer-max>, title: [Max Horkheimer])[]
#person(<neurath-otto>, title: [Otto Neurath])[]
#person(<carnap-rudolf>, title: [Rudolf Carnap])[]
